### ISSUE TITLE
error while training the retinamask for COCO dataset with my own images inside

### ISSUE THREAD

**Issue by amardeepjaiman** [chengyangfu/retinamask#12]
## 🐛 Bug
Error while starting the training using tools/train_net.py

I have my own dataset in COCO format on which i want to train the retinamask. I am getting following error while starting the training.

**Traceback (most recent call last):
  File "tools/train_net.py", line 18, in <module>
    from maskrcnn_benchmark.engine.inference import inference
  File "/data/home/amjn_cowi/amardeep/retinamask/retinamask/maskrcnn_benchmark/engine/inference.py", line 20, in <module>
    from maskrcnn_benchmark.structures.boxlist_ops import boxlist_iou
  File "/data/home/amjn_cowi/amardeep/retinamask/retinamask/maskrcnn_benchmark/structures/boxlist_ops.py", line 6, in <module>
    from maskrcnn_benchmark.layers import nms as _box_nms
  File "/data/home/amjn_cowi/amardeep/retinamask/retinamask/maskrcnn_benchmark/layers/__init__.py", line 8, in <module>
    from .nms import nms
  File "/data/home/amjn_cowi/amardeep/retinamask/retinamask/maskrcnn_benchmark/layers/nms.py", line 3, in <module>
    from maskrcnn_benchmark import _C
ImportError: cannot import name '_C' from 'maskrcnn_benchmark' (/data/home/amjn_cowi/amardeep/retinamask/retinamask/maskrcnn_benchmark/__init__.py)**

Can somebody guide me how to fix it ?

I used following command to start the training :
python tools/train_net.py --config-file=configs/retina/retinanet_mask_R-50-FPN_1.5x.yaml

I followed the MaskRCNN Benchmark (install.md) file to setup the environment.

Thanks in Advance

**Comment by chengyangfu** [comment]
Hi, 
   Looks like to didn't build the code properly.  Try the following script to rebuild the project. 
```
rm -rf build
python setup.py build develop
```
